# Generated by Django 5.0.6 on 2026-04-03 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('domain_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllowedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('allow_type', models.CharField(choices=[('exact', 'Exact'), ('wildcard', 'Wildcard'), ('regex', 'Regex')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('block_type', models.CharField(choices=[('exact', 'Exact match'), ('wildcard', 'Wildcard (blocks all subdomains)'), ('regex', 'Regular expression')], max_length=10)),
                ('layer', models.CharField(choices=[('proxy', 'DNS proxy (fastest)'), ('unbound', 'Unbound local-zone')], default='proxy', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('last_hit', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=255)),
                ('pattern_type', models.CharField(choices=[('extension', 'File extension (e.g. .js, .gif)'), ('keyword', 'Domain keyword (e.g. ads, track)'), ('regex', 'Full regex on domain'), ('path_keyword', 'URL path keyword')], max_length=15)),
                ('enabled', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GravityDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('adlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.adlist')),
            ],
            options={
                'indexes': [models.Index(fields=['domain'], name='blocks_grav_domain_4182e3_idx')],
                'unique_together': {('domain', 'adlist')},
            },
        ),
    ]
