# Generated by Django 5.0.6 on 2026-04-03 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_blockgroup_adlist_group_alloweddomain_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('domains', models.TextField(help_text='Comma-separated list of domains or patterns')),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AppControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='blocks.appcategory')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_controls', to='blocks.blockgroup')),
            ],
            options={
                'unique_together': {('category', 'group')},
            },
        ),
    ]
