# Generated by Django 5.0.6 on 2026-04-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafeSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('strict', 'Strict'), ('moderate', 'Moderate')], default='strict', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('client_ip', models.GenericIPAddressField(db_index=True)),
                ('status', models.CharField(choices=[('allowed', 'Allowed'), ('blocked_pattern', 'Blocked by pattern'), ('blocked_domain', 'Blocked by domain rule'), ('blocked_list', 'Blocked by blocklist'), ('nxdomain', 'NXDOMAIN from upstream')], max_length=20)),
                ('matched_rule', models.CharField(blank=True, max_length=255)),
                ('response_time_ms', models.FloatField(default=0)),
                ('resolved_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('query_type', models.CharField(default='A', max_length=10)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='dns_querylo_timesta_87df6f_idx'), models.Index(fields=['client_ip', '-timestamp'], name='dns_querylo_client__0a1a20_idx'), models.Index(fields=['status', '-timestamp'], name='dns_querylo_status_dbb824_idx')],
            },
        ),
    ]
