# Generated by Django 5.0.6 on 2026-04-03 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_blockgroup_adlist_group_alloweddomain_group_and_more'),
        ('dns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='wg0', max_length=100)),
                ('private_key', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=100)),
                ('listen_port', models.IntegerField(default=51820)),
                ('address', models.CharField(default='10.0.0.1/24', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='hostname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='mac',
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='os_hint',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='vendor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='blocks.blockgroup'),
        ),
        migrations.CreateModel(
            name='VPNPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('private_key', models.CharField(blank=True, max_length=100)),
                ('public_key', models.CharField(max_length=100)),
                ('allowed_ips', models.CharField(default='10.0.0.2/32', max_length=100)),
                ('last_handshake', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_peers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
