# Generated by Django 5.0.6 on 2026-04-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0002_vpnserver_client_hostname_client_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylog',
            name='status',
            field=models.CharField(choices=[('allowed', 'Allowed'), ('blocked_pattern', 'Blocked by pattern'), ('blocked_domain', 'Blocked by domain rule'), ('blocked_list', 'Blocked by blocklist'), ('blocked_ai', 'Blocked by AI heuristic'), ('nxdomain', 'NXDOMAIN from upstream')], max_length=20),
        ),
    ]
