# Generated by Django 5.0.6 on 2026-04-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0003_alter_querylog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='dnssec_status',
            field=models.CharField(db_index=True, default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='querylog',
            name='resolved_by',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='ttl',
            field=models.IntegerField(default=0),
        ),
    ]
