# Generated by Django 5.0.6 on 2026-04-06 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_appcategory_appcontrol'),
        ('dns', '0004_querylog_dnssec_status_querylog_resolved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('malware_hit', 'Malware/Threat Domain Hit'), ('new_device', 'New Device Joined Network'), ('shield_expire', 'Shield Disable Expired'), ('gravity_fail', 'Gravity Update Failed'), ('high_volume', 'Unusually High Query Volume')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('telegram', 'Telegram'), ('webhook', 'Webhook')], max_length=20)),
                ('destination', models.CharField(help_text='Email, webhook URL, Telegram chat ID, or Slack webhook', max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('domain', 'Domain'), ('pattern', 'Pattern'), ('app_category', 'App Category')], max_length=20)),
                ('target', models.CharField(help_text='Domain, pattern text, or app category name', max_length=255)),
                ('days', models.CharField(default='Mon,Tue,Wed,Thu,Fri', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blocks.blockgroup')),
            ],
        ),
    ]
