# Generated by Django 5.0.6 on 2026-04-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0005_v21_scheduled_alerts_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='device_type',
            field=models.CharField(default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
