# Generated by Django 5.0.6 on 2026-04-06 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0006_v21_client_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(help_text='e.g., domain_explain, app_generator', max_length=50)),
                ('query', models.CharField(help_text='The domain or app name being processed', max_length=255)),
                ('prompt', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('tokens_estimate', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
