# Generated by Django 5.0.6 on 2026-07-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0007_aiusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='status',
            field=models.CharField(default='ok', max_length=20),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='tokens_input',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='tokens_output',
            field=models.IntegerField(default=0),
        ),
    ]
