# Generated by Django 5.0.6 on 2026-07-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0008_ai_usage_provider_model_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_blocked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='status',
            field=models.CharField(choices=[('allowed', 'Allowed'), ('blocked_pattern', 'Blocked by pattern'), ('blocked_domain', 'Blocked by domain rule'), ('blocked_list', 'Blocked by blocklist'), ('blocked_ai', 'Blocked by AI heuristic'), ('blocked_client', 'Blocked by client ban'), ('nxdomain', 'NXDOMAIN from upstream')], max_length=20),
        ),
    ]
