# Generated by Django 5.0.6 on 2026-07-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0009_client_is_blocked_and_blocked_client_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainTrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('trust_score', models.PositiveSmallIntegerField(db_index=True, default=50)),
                ('label', models.CharField(choices=[('safe', 'Safe'), ('tracking', 'Tracking'), ('malicious', 'Malicious'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, default='', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trust_score', 'domain'],
            },
        ),
    ]
