# Generated by Django 5.0.6 on 2026-07-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0010_domain_trust'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='open_ports',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
