# Generated by Django 5.0.6 on 2026-07-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0011_client_open_ports'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCnameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('target', models.CharField(max_length=255)),
                ('ttl', models.PositiveIntegerField(default=300)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='LocalDnsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('ttl', models.PositiveIntegerField(default=300)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
    ]
