# Generated by Django 5.0.6 on 2026-07-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0012_local_dns_and_cname'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='shield_bypass',
            field=models.BooleanField(db_index=True, default=False, help_text='When true, DNS Shield filtering is fully disabled for this client IP'),
        ),
    ]
