# Generated by Django 5.0.6 on 2026-08-31 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0016_client_route_via_tor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogExcludedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('rule_type', models.CharField(choices=[('exact', 'Exact match'), ('wildcard', 'Wildcard (includes subdomains)'), ('regex', 'Regular expression')], default='exact', max_length=15)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('last_hit', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
